export const FETCH_RETREATS_STARTED = 'FETCH_RETREATS_STARTED'
export const FETCH_RETREATS_SUCCEED = 'FETCH_RETREATS_SUCCEED'
export const FETCH_RETREATS_FAILED = 'FETCH_RETREATS_FAILED'

export const CREATE_RETREAT_STARTED = 'CREATE_RETREAT_STARTED'
export const CREATE_RETREAT_SUCCEED = 'CREATE_RETREAT_SUCCEED'
export const CREATE_RETREAT_FAILED = 'CREATE_RETREAT_SUCCEED'

export const CLEAR_CREATE_RETREAT = 'CLEAR_CREATE_RETREAT'

export const FETCH_RETREAT_STARTED = 'FETCH_RETREAT_STARTED'
export const FETCH_RETREAT_SUCCEED = 'FETCH_RETREAT_SUCCEED'
export const FETCH_RETREAT_FAILED = 'FETCH_RETREAT_FAILED'

export const FETCH_DISHES_FOR_MEAL_STARTED = 'FETCH_DISHES_FOR_MEAL_STARTED'
export const FETCH_DISHES_FOR_MEAL_SUCCEED = 'FETCH_DISHES_FOR_MEAL_SUCCEED'
export const FETCH_DISHES_FOR_MEAL_FAILED = 'FETCH_DISHES_FOR_MEAL_FAILED'
