export const FETCH_RETREATS_STARTED = 'FETCH_RETREATS_STARTED'
export const FETCH_RETREATS_SUCCEED = 'FETCH_RETREATS_SUCCEED'
export const FETCH_RETREATS_FAILED = 'FETCH_RETREATS_FAILED'

export const CREATE_RETREAT_STARTED = 'CREATE_RETREAT_STARTED'
export const CREATE_RETREAT_SUCCEED = 'CREATE_RETREAT_SUCCEED'
export const CREATE_RETREAT_FAILED = 'CREATE_RETREAT_SUCCEED'

export const CLEAR_CREATE_RETREAT = 'CLEAR_CREATE_RETREAT'

export const FETCH_RETREAT_STARTED = 'FETCH_RETREAT_STARTED'
export const FETCH_RETREAT_SUCCEED = 'FETCH_RETREAT_SUCCEED'
export const FETCH_RETREAT_FAILED = 'FETCH_RETREAT_FAILED'

export const FETCH_DISHES_FOR_MEAL_STARTED = 'FETCH_DISHES_FOR_MEAL_STARTED'
export const FETCH_DISHES_FOR_MEAL_SUCCEED = 'FETCH_DISHES_FOR_MEAL_SUCCEED'
export const FETCH_DISHES_FOR_MEAL_FAILED = 'FETCH_DISHES_FOR_MEAL_FAILED'

export const UPDATE_RETREAT_STARTED = 'UPDATE_RETREAT_STARTED'
export const UPDATE_RETREAT_SUCCEED = 'UPDATE_RETREAT_SUCCEED'
export const UPDATE_RETREAT_FAILED = 'UPDATE_RETREAT_FAILED'

export const DELETE_RETREAT_STARTED = 'DELETE_RETREAT_STARTED'
export const DELETE_RETREAT_SUCCEED = 'DELETE_RETREAT_SUCCEED'
export const DELETE_RETREAT_FAILED = 'DELETE_RETREAT_FAILED'

export const CREATE_MEAL_STARTED = 'CREATE_MEAL_STARTED'
export const CREATE_MEAL_SUCCEED = 'CREATE_MEAL_SUCCEED'
export const CREATE_MEAL_FAILED = 'CREATE_MEAL_FAILED'

export const DELETE_MEAL_STARTED = 'DELETE_MEAL_STARTED'
export const DELETE_MEAL_SUCCEED = 'DELETE_MEAL_SUCCEED'
export const DELETE_MEAL_FAILED = 'DELETE_MEAL_FAILED'

export const UPDATE_MEAL_STARTED = 'UPDATE_MEAL_STARTED'
export const UPDATE_MEAL_SUCCEED = 'UPDATE_MEAL_SUCCEED'
export const UPDATE_MEAL_FAILED = 'UPDATE_MEAL_FAILED'

export const CREATE_DISH_STARTED = 'CREATE_DISH_STARTED'
export const CREATE_DISH_SUCCEED = 'CREATE_DISH_SUCCEED'
export const CREATE_DISH_FAILED = 'CREATE_DISH_FAILED'

export const DELETE_DISH_STARTED = 'DELETE_DISH_STARTED'
export const DELETE_DISH_SUCCEED = 'DELETE_DISH_SUCCEED'
export const DELETE_DISH_FAILED = 'DELETE_DISH_FAILED'


export const FETCH_INGREDIENTS_FOR_DISH_STARTED = 'FETCH_INGREDIENTS_FOR_DISH_STARTED'
export const FETCH_INGREDIENTS_FOR_DISH_SUCCEED = 'FETCH_INGREDIENTS_FOR_DISH_SUCCEED'
export const FETCH_INGREDIENTS_FOR_DISH_FAILED = 'FETCH_INGREDIENTS_FOR_DISH_FAILED'

export const CREATE_INGREDIENT_STARTED = 'CREATE_INGREDIENT_STARTED'
export const CREATE_INGREDIENT_SUCCEED = 'CREATE_INGREDIENT_SUCCEED'
export const CREATE_INGREDIENT_FAILED = 'CREATE_INGREDIENT_FAILED'

export const UPDATE_INGREDIENT_STARTED = 'UPDATE_INGREDIENT_STARTED'
export const UPDATE_INGREDIENT_SUCCEED = 'UPDATE_INGREDIENT_SUCCEED'
export const UPDATE_INGREDIENT_FAILED = 'UPDATE_INGREDIENT_FAILED'

export const DELETE_INGREDIENT_STARTED = 'DELETE_INGREDIENT_STARTED'
export const DELETE_INGREDIENT_SUCCEED = 'DELETE_INGREDIENT_SUCCEED'
export const DELETE_INGREDIENT_FAILED = 'DELETE_INGREDIENT_FAILED'
