import { Retreat } from "store/retreats/types";

export const retreats: Retreat[] = [
  { id: 1, name: 'Korona party', mealsCount: 3, carts: 1 },
  { id: 2, name: 'Przyjęcie staruszków', mealsCount: 30, carts: 3 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Wesele młodych bombelków', mealsCount: 9, carts: 5 },
  { id: 1, name: 'Lolek i Bolek', mealsCount: 9, carts: 5 },
]
