import { Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, Input, InputLabel, Radio, RadioGroup } from '@material-ui/core'
import { CreateCartOptions, CreateCartType } from 'components/Carts/types/create-cart.type'
import Token from 'components/Token'
import moment from 'moment'
import React, { useState } from 'react'
import { MOMENT_DATE_FORMAT } from 'utils/constants'


interface AddCartModalProps {
  open: boolean
  retreatId: number
  onClose: () => void
  onCreateCart: (options: CreateCartOptions) => void
}

const getCurrentDate = () => {
  return moment().format(MOMENT_DATE_FORMAT)
}

const getWeekAgoDate = () => {
  return moment().subtract(7, 'days').format(MOMENT_DATE_FORMAT)
}

const AddCartModal = ({ open, onClose, onCreateCart, retreatId }: AddCartModalProps) => {
  const [selectedCart, setSelectedCart] = useState<CreateCartType>("empty")
  const [selectedDateFrom, setSelectedDateFrom] = useState(getWeekAgoDate());
  const [selectedDateTo, setSelectedDateTo] = useState(getCurrentDate());

  const handleChange = (e: any) => {
    setSelectedCart(e.target.value)
  }

  return (
    <Dialog open={open} onClose={onClose} fullWidth>
      <DialogTitle><Token value="createNewCart" /> </DialogTitle>
      <DialogContent>
        <FormControl component="fieldset">
          <RadioGroup name="cartType" value={selectedCart} onChange={handleChange}>
            <FormControlLabel value={"empty"} control={<Radio />} label={<Token value="emptyCart" />} />
            <FormControlLabel value={"generated"} control={<Radio />} label={<Token value="autoGeneratedCart" />} />
          </RadioGroup>
        </FormControl>
        <div style={{ margin: 10 }} />
        <FormControl fullWidth disabled={selectedCart !== 'generated'}>
          <InputLabel><Token value="cartDateFrom" /></InputLabel>
          <Input value={selectedDateFrom} onChange={e => setSelectedDateFrom(e.target.value)} type="date" />
        </FormControl>
        <FormControl fullWidth disabled={selectedCart !== 'generated'}>
          <InputLabel><Token value="cartDateTo" /></InputLabel>
          <Input value={selectedDateTo} onChange={e => setSelectedDateTo(e.target.value)} type="date" />
        </FormControl>

      </DialogContent>

      <DialogActions>
        <Button onClick={onClose} color="secondary">
          <Token value="cancel" />
        </Button>
        <Button
          onClick={() => onCreateCart({
            type: selectedCart,
            from: selectedDateFrom,
            to: selectedDateTo,
          })}
          color="primary"
        >
          <Token value="create" />
        </Button>
      </DialogActions>
    </Dialog>
  )
}

export default AddCartModal
